### ISSUE TITLE
Modify proxy yml properties to not depend on service

### ISSUE THREAD

**Issue by Flashky** [Flashky/notifier-packt#61]
Currently, proxies are define like this:

```yml
service:
  proxy:
    # Do not add with 'http://' at the beginning!
    host: myproxy.host.com
    port: 8080
```

It must be:
```yml
proxy:
  # Do not add with 'http://' at the beginning!
  host: myproxy.host.com
  port: 8080
```
Modify also ``ProxyProperty`` class.
